# Generated by Django 5.1.3 on 2024-11-28 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('boat_class', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(max_length=100)),
                ('size', models.IntegerField()),
            ],
        ),
    ]
