# Generated by Django 5.1.3 on 2024-11-28 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watersports', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boat',
            old_name='number',
            new_name='adult_capacity',
        ),
        migrations.RenameField(
            model_name='boat',
            old_name='size',
            new_name='child_capacity',
        ),
        migrations.AlterField(
            model_name='boat',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
