# Generated by Django 5.1.3 on 2024-11-28 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watersports', '0002_rename_number_boat_adult_capacity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boat',
            old_name='boat_class',
            new_name='model',
        ),
    ]
